name: Database Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      # Cache node_modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: modules${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm install
      - run: npm run build
      # Upload only build artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      # Cache node_modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: modules${{ hashFiles('package-lock.json') }}
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist/
      # OpenSearch
      - name: Build OpenSearch image
        run: |
          cd src/opensearch
          docker build -t opensearch-test .

      - name: Start OpenSearch container
        run: |
          docker run -d \
            -e "discovery.type=single-node" \
            -e "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Password1!rohu656UHhhh" \
            -p 9200:9200 -p 9600:9600 \
            opensearch-test
      # PostgreSQL
      - name: Build PostgreSQL image
        run: |
          cd src/pgsql
          docker build -t postgres-test .

      - name: Start PostgreSQL container
        run: |
          docker run -d \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_DB=local_db \
            -p 5432:5432 \
            postgres-test
      # Wait for services to be ready
      - name: Wait for services
        run: |
          timeout 60s bash -c '
          until curl -sf https://localhost:9200 -ku "admin:Password1!rohu656UHhhh"; do
            echo "Waiting for OpenSearch..."
            sleep 5
          done
          until PGPASSWORD=postgres psql -h localhost -U postgres -d local_db -c "\l" > /dev/null 2>&1; do
            echo "Waiting for PostgreSQL..."
            sleep 5
          done'

      - name: Run DB tests
        run: npm run test