name: Database Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Build and start OpenSearch container
      - name: Build and start OpenSearch
        run: |
          cd src/opensearch
          docker build -t opensearch-test .
          docker run -d \
            -e "discovery.type=single-node" \
            -e "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Password1!rohu656UHhhh" \
            -p 9200:9200 -p 9600:9600 \
            opensearch-test

      # Build and start PostgreSQL container
      - name: Build and start PostgreSQL
        run: |
          cd src/pgsql
          docker build -t postgres-test .
          docker run -d \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_DB=local_db \
            -p 5432:5432 \
            postgres-test

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # Wait for services to be ready
      - name: Wait for services
        run: |
          timeout 60s bash -c '
          until curl -sf https://localhost:9200 -ku "admin:Password1!rohu656UHhhh"; do
            echo "Waiting for OpenSearch..."
            sleep 5
          done
          until PGPASSWORD=postgres psql -h localhost -U postgres -d local_db -c "\l" > /dev/null 2>&1; do
            echo "Waiting for PostgreSQL..."
            sleep 5
          done'

      - name: Run tests
        run: npm test